name: Bun.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [1.x]
        # See supported Bun.js release schedule at https://bun.sh/docs/installation#github-actions

    steps:
    - uses: actions/checkout@v6
    - name: Use Bun.js ${{ matrix.bun-version }}
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ matrix.bun-version }}
        cache: true
    - run: bun install
      working-directory: ./frontend
    - run: bun run build
    - run: bun test
      continue-on-error: true
    - run: bun run eslint
      continue-on-error: true
    - run: bun run prettier
      continue-on-error: true
